services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - SIGNUPS_ALLOWED=${VW_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${VW_ADMIN_TOKEN}
      - DOMAIN=http://vault.${ATLAS_HOSTNAME}.${BASE_DOMAIN}
    volumes:
      - ${DATA_ROOT}/vaultwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(vault.${ATLAS_HOSTNAME}.${BASE_DOMAIN})"
      - "traefik.http.routers.vault.entrypoints=web"
      - "traefik.http.services.vault.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
