services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - SIGNUPS_ALLOWED=${VW_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${VW_ADMIN_TOKEN}
      - DOMAIN=http://${ATLAS_HOSTNAME}.${BASE_DOMAIN}/vault
    volumes:
      - ${DATA_ROOT}/vaultwarden:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/vault`)
      - traefik.http.services.vault.loadbalancer.server.port=80
      - traefik.http.routers.vault.middlewares=vault-strip
      - traefik.http.middlewares.vault-strip.stripprefix.prefixes=/vault
      - traefik.http.routers.vault.priority=10
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
