services:
  gitea:
    image: gitea/gitea:1.22
    container_name: gitea
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - GITEA__server__ROOT_URL=http://${ATLAS_HOSTNAME}.${BASE_DOMAIN}/gitea
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
      - GITEA__mailer__ENABLED=false
    volumes:
      - ${DATA_ROOT}/gitea:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/gitea`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.routers.gitea.middlewares=gitea-strip
      - traefik.http.middlewares.gitea-strip.stripprefix.prefixes=/gitea
      - traefik.http.routers.gitea.priority=10
    restart: unless-stopped
    networks:
      - atlas_net

  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ${DATA_ROOT}/couchdb:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.http.routers.couchdb.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/couchdb`)
      - traefik.http.services.couchdb.loadbalancer.server.port=5984
      - traefik.http.routers.couchdb.middlewares=couchdb-strip
      - traefik.http.middlewares.couchdb-strip.stripprefix.prefixes=/couchdb
      - traefik.http.routers.couchdb.priority=10
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
