services:
  nextcloud-db:
    image: postgres:15
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - atlas_net
    volumes:
      - ${DATA_ROOT}/nextcloud/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}

  nextcloud-redis:
    image: redis:7
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - atlas_net
    volumes:
      - ${DATA_ROOT}/nextcloud/redis:/data

  nextcloud:
    image: nextcloud:28
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - atlas_net
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASS}
      NEXTCLOUD_TRUSTED_DOMAINS: ${ATLAS_HOSTNAME}.${BASE_DOMAIN}
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: ${NEXTCLOUD_DB}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}
      REDIS_HOST: nextcloud-redis
    volumes:
      - ${DATA_ROOT}/nextcloud/html:/var/www/html
      - ${DATA_ROOT}/nextcloud/data:/var/www/html/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/nextcloud`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.middlewares=nextcloud-strip
      - traefik.http.middlewares.nextcloud-strip.stripprefix.prefixes=/nextcloud
      - traefik.http.routers.nextcloud.priority=10

  nextcloud-cron:
    image: nextcloud:28
    container_name: nextcloud-cron
    restart: unless-stopped
    networks:
      - atlas_net
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - ${DATA_ROOT}/nextcloud/html:/var/www/html
      - ${DATA_ROOT}/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
