services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:${TRAEFIK_HTTP_PORT}
      # enable dashboard
      - --api.dashboard=true
      # TLS can be enabled later; for LAN-only HTTP is fine.
      # - --entrypoints.websecure.address=:${TRAEFIK_HTTPS_PORT}
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      # - "${TRAEFIK_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - atlas_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/traefik`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.priority=100

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
