version: "3.9"
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:${TRAEFIK_HTTP_PORT}
      # TLS can be enabled later; for LAN-only HTTP is fine.
      #- --entrypoints.websecure.address=:${TRAEFIK_HTTPS_PORT}
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      # - "${TRAEFIK_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - atlas


networks:
  atlas:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}