services:
  ocis:
    environment:
      # ── Core ──────────────────────────────────────────────
      OCIS_INSECURE: "true"
      OCIS_URL: "http://${ATLAS_HOSTNAME}.${BASE_DOMAIN}/ocis"
      OCIS_LOG_LEVEL: "info"

      # ── Secrets ───────────────────────────────────────────
      OCIS_JWT_SECRET: "${OCIS_JWT_SECRET}"
      OCIS_MACHINE_AUTH_API_KEY: "${OCIS_MACHINE_AUTH_API_KEY}"
      OCIS_TRANSFER_SECRET: "${OCIS_TRANSFER_SECRET}"

      # ── Identity ──────────────────────────────────────────
      OCIS_ADMIN_USER: "${OCIS_ADMIN_USER}"
      OCIS_ADMIN_PASS: "${OCIS_ADMIN_PASS}"
      OCIS_ADMIN_USER_ID: "${OCIS_ADMIN_USER_ID}"
      OCIS_SYSTEM_USER_ID: "${OCIS_SYSTEM_USER_ID}"
      PROXY_USER_ID: "${PROXY_USER_ID}"

      # ── Storage Users ─────────────────────────────────────
      STORAGE_USERS_DRIVER: "ocis"
      STORAGE_USERS_OCIS_ROOT: "/var/lib/ocis/storage/users"
      STORAGE_USERS_MOUNT_ID: "${STORAGE_USERS_MOUNT_ID}"
      GATEWAY_STORAGE_USERS_MOUNT_ID: "${STORAGE_USERS_MOUNT_ID}"

      # ── Events (external NATS) ────────────────────────────
      EVENTS_ENDPOINT: "nats://ocis-nats:4222"
      EVENTS_ENABLE: "true"
      NATS_ENABLE: "false"

      # ── Disable LDAP everywhere ───────────────────────────
      IDM_LDAP_ENABLE: "false"
      GRAPH_LDAP_ENABLE: "false"
      USERS_LDAP_ENABLE: "false"
      GROUPS_LDAP_ENABLE: "false"
      AUTH_BASIC_LDAP_ENABLE: "false"

      # Force drivers/providers to built-in IDM
      GRAPH_DRIVER: "ocis"
      USERS_DRIVER: "ocis"
      GROUPS_DRIVER: "ocis"
      AUTH_BASIC_DRIVER: "ocis"

      # ── Service account & system user ─────────────────────
      STORAGE_SYSTEM_USER_ID: "${OCIS_SYSTEM_USER_ID}"
      STORAGE_SYSTEM_USER_API_KEY: "${OCIS_SYSTEM_USER_API_KEY}"
      OCIS_SYSTEM_USER_API_KEY: "${OCIS_SYSTEM_USER_API_KEY}"
      OCIS_SERVICE_ACCOUNT_ID: "${OCIS_SERVICE_ACCOUNT_ID}"
      OCIS_SERVICE_ACCOUNT_SECRET: "${OCIS_SERVICE_ACCOUNT_SECRET}"

      # ── IDM builtin provider ──────────────────────────────
      OCIS_IDENTITY_PROVIDERS: "ocis"
      IDM_ADMIN_PASSWORD: "${IDM_ADMIN_PASSWORD}"
      IDM_BIND_PASSWORD: "${IDM_BIND_PASSWORD}"
