services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    environment:
      - OCIS_INSECURE=true
      - OCIS_URL=http://${ATLAS_HOSTNAME}.${BASE_DOMAIN}/ocis
      - OCIS_JWT_SECRET=${OCIS_JWT_SECRET}
      - OCIS_MACHINE_AUTH_API_KEY=${OCIS_MACHINE_AUTH_API_KEY}
      - OCIS_TRANSFER_SECRET=${OCIS_TRANSFER_SECRET}
      - OCIS_ADMIN_USER_ID=958d7151-528b-42b1-9e3a-fc9e7f1f5d34
      - STORAGE_USERS_MOUNT_ID=${STORAGE_USERS_MOUNT_ID}
      - OCIS_SYSTEM_USER_ID=admin
      - PROXY_USER_ID=admin
    volumes:
      - ${DATA_ROOT}/ocis:/var/lib/ocis
    labels:
      - traefik.enable=true
      - traefik.http.routers.ocis.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/ocis`)
      - traefik.http.services.ocis.loadbalancer.server.port=9200
      - traefik.http.routers.ocis.middlewares=ocis-strip
      - traefik.http.middlewares.ocis-strip.stripprefix.prefixes=/ocis
      - traefik.http.routers.ocis.priority=10
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
