services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    environment:
      - OCIS_INSECURE=true
      - OCIS_URL=http://cloud.${ATLAS_HOSTNAME}.${BASE_DOMAIN}
      - OCIS_JWT_SECRET=${OCIS_JWT_SECRET}
      - OCIS_MACHINE_AUTH_API_KEY=${OCIS_MACHINE_AUTH_API_KEY}
      - OCIS_ADMIN_USER_ID=958d7151-528b-42b1-9e3a-fc9e7f1f5d34
      - OCIS_SYSTEM_USER_ID=admin
      - PROXY_USER_ID=admin
    volumes:
      - ${DATA_ROOT}/ocis:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.rule=Host(`cloud.${ATLAS_HOSTNAME}.${BASE_DOMAIN}`)"
      - "traefik.http.routers.ocis.entrypoints=web"
    restart: unless-stopped
    networks:
      - atlas
