services:
  nextcloud:
    image: nextcloud:28-fpm
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASS}
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - /srv/atlas/nextcloud/html:/var/www/html
      - /srv/atlas/nextcloud/custom_apps:/var/www/html/custom_apps
      - /srv/atlas/nextcloud/config:/var/www/html/config
      - /srv/atlas/nextcloud/data:/var/www/html/data
    networks:
      - atlas_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/nextcloud`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.middlewares=nextcloud-strip
      - traefik.http.middlewares.nextcloud-strip.stripprefix.prefixes=/nextcloud
      - traefik.http.routers.nextcloud.priority=10

  nextcloud-cron:
    image: nextcloud:28-fpm
    container_name: nextcloud-cron
    restart: unless-stopped
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - /srv/atlas/nextcloud/html:/var/www/html
      - /srv/atlas/nextcloud/custom_apps:/var/www/html/custom_apps
      - /srv/atlas/nextcloud/config:/var/www/html/config
      - /srv/atlas/nextcloud/data:/var/www/html/data
    networks:
      - atlas_net

  nextcloud-db:
    image: postgres:15
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
    volumes:
      - /srv/atlas/nextcloud/db:/var/lib/postgresql/data
    networks:
      - atlas_net

  nextcloud-redis:
    image: redis:7
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
