services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "http://${ATLAS_HOSTNAME}.${BASE_DOMAIN}/ocis"
      OCIS_LOG_LEVEL: "info"

      OCIS_JWT_SECRET: "${OCIS_JWT_SECRET}"
      OCIS_MACHINE_AUTH_API_KEY: "${OCIS_MACHINE_AUTH_API_KEY}"
      OCIS_TRANSFER_SECRET: "${OCIS_TRANSFER_SECRET}"

      OCIS_ADMIN_USER: "${OCIS_ADMIN_USER}"
      OCIS_ADMIN_PASS: "${OCIS_ADMIN_PASS}"
      OCIS_ADMIN_USER_ID: "${OCIS_ADMIN_USER_ID}"
      OCIS_SYSTEM_USER_ID: "${OCIS_SYSTEM_USER_ID}"
      PROXY_USER_ID: "${PROXY_USER_ID}"

      STORAGE_USERS_DRIVER: "ocis"
      STORAGE_USERS_OCIS_ROOT: "/var/lib/ocis/storage/users"
      STORAGE_USERS_MOUNT_ID: "${STORAGE_USERS_MOUNT_ID}"

      # NEW → gateway + external NATS
      GATEWAY_STORAGE_USERS_MOUNT_ID: "${STORAGE_USERS_MOUNT_ID}"
      EVENTS_ENDPOINT: nats://ocis-nats:4222
      EVENTS_ENABLE: "true"
      NATS_ENABLE: "false"

    volumes:
      - /srv/atlas/ocis:/var/lib/ocis

    labels:
      - traefik.enable=true
      - traefik.http.routers.ocis.rule=Host(`${ATLAS_HOSTNAME}.${BASE_DOMAIN}`) && PathPrefix(`/ocis`)
      - traefik.http.services.ocis.loadbalancer.server.port=9200
      - traefik.http.routers.ocis.middlewares=ocis-strip
      - traefik.http.middlewares.ocis-strip.stripprefix.prefixes=/ocis
      - traefik.http.routers.ocis.priority=10

    restart: unless-stopped
    networks:
      - atlas_net

  # External NATS (message bus)
  ocis-nats:
    image: nats:2
    container_name: ocis-nats
    command: ["-js"] # enable JetStream
    ports:
      - "4222"       # NATS client connections
      - "8222"       # NATS monitoring (optional)
    volumes:
      - /srv/atlas/ocis/nats:/data
    restart: unless-stopped
    networks:
      - atlas_net

networks:
  atlas_net:
    external: true
    name: ${ATLAS_DOCKER_NETWORK}
