global:
  resolve_timeout: 5m

route:
  receiver: ntfy
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: ntfy
    webhook_configs:
      - url: http://ntfy:80/
        send_resolved: true