global:
  scrape_interval: 15s

rule_files:
  - "prometheus-alerts.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node_exporter
    static_configs:
      - targets: ['localhost:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

remote_write:
  - url: http://victoriametrics:8428/api/v1/write

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
